# Generated by Django 2.2.4 on 2020-12-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginReg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newusers',
            table='NewUsers',
        ),
    ]
