# Generated by Django 2.2.4 on 2020-12-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginReg', '0003_auto_20201228_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newusers',
            name='gender',
            field=models.CharField(max_length=2),
        ),
    ]
