# Generated by Django 2.2.4 on 2020-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
