# Generated by Django 2.2.4 on 2020-12-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='Emp',
        ),
    ]
